### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by Zerka30** [zifeo/terraform-openstack-rke2#15]
I tried to deploy a k8s cluster on Infomaniak Public Cloud. Everything seems deploy, but when I execute this : `kubectl --kubeconfig single-server.rke2.yaml get nodes`. I get the following error

```XXXX@XPS:~/Workspace/terraform-openstack-rke2/examples/single-server$ kubectl --kubeconfig single-server.rke2.yaml get nodes E0714 15:03:30.315163   34825 memcache.go:265] couldn't get current server API group list: Get "https://<public_ip>:6443/api?timeout=32s": EOF```

**Comment by zifeo** [comment]
@Zerka30 can you share your terraform code?

**Comment by Zerka30** [comment]
Hi @zifeo ,

I just use the example located at https://github.com/zifeo/terraform-openstack-rke2/tree/main/examples/single-server

**Comment by zifeo** [comment]
@Zerka30 This is weird, the example has no issue on my side. Do you confirm that the `terraform apply` successfully complete and the tube config looks valid? When you look at Horizon's dashboard, can you check that the load balancer is available and working (then check all of its target)?

**Comment by Zerka30** [comment]
I tried to redeploy with same configuration, and seems works now ! :man_shrugging:
