### ISSUE TITLE
The VIP port doesn't seem to work

### ISSUE THREAD

**Issue by mhazan01** [zifeo/terraform-openstack-rke2#37]
Hello again,

i've used the 2.x version to deploy a working cluster. and now i'm trying to deploy a new one with the latest version. however it seems that the VIP never get assigned to the network port ? i can see the floating ip and the local port created but the network itself doesn't works. are there new openstack service required since 2.x to make that work ?

**Comment by mhazan01** [comment]
possibly fixed by this ?
https://docs.mirantis.com/mcp/q4-18/mcp-operations-guide/tshooting/tshoot-contrail/tshoot-os-oc/fip-not-associated-lb.html
and adding allowed address pair 0.0.0.0/0 (security be damned)

**Comment by zifeo** [comment]
@mhazan01 did you follow the migration [guide](https://github.com/zifeo/terraform-openstack-rke2?tab=readme-ov-file#from-v2-to-v3)? if yes, can you share your config file?

**Comment by mhazan01** [comment]
hey i didn't migrate, i deployed a brand new cluster, i'll share the config files tomorrow. it's my own instance of openstack deployed with kolla-ansible (should be latest or -1)

**Comment by mhazan01** [comment]
this is my main.tf file 
[zifeo.txt](https://github.com/user-attachments/files/15882535/zifeo.txt)

**Comment by mhazan01** [comment]
welp, for some reason this morning the floating ip seems to associate automatically, either i was blind and didn't read the right line in the openstack floating ip list, or there was some broken interactions from a previous apply ? i'm still working around some other issue but they might be related to my own openstack networking setup.

**Comment by zifeo** [comment]
Sure! Let me know if something else arise, no issues along that line on the tens of cluster we manage daily :)

**Comment by mhazan01** [comment]
i think i changed the network.tf to have the resource "openstack_networking_floatingip_associate_v2" "fip" block at the end of the file. but i'm not sure that's what fixed it for me. i'm also fighting with the yq command but that's not a big hurdle.
