### ISSUE TITLE
[OCTAVIA] HA Interface on router in Yoga makes the 3rd cidr ip in load balancer subnet unavailable

### ISSUE THREAD

**Issue by bagutzu** [zifeo/terraform-openstack-rke2#8]
Hello,

I am encountering the following exception on an openstack deployment with HA Router interfaces.

`exceptions.ProviderDriverError: Provider 'octavia' reports error: IP address 10.1.3.3 already allocated in subnet 1e774ecf-99e0-44db-a1b8-4693fe1a3766`

Would you be open to a PR where we make the local.internal_ip variable an actual variable and not a local one ? Do you have any contribution rules/guides ?

Changing the lb_provider hardcoded string to a variable to support the new openstack versions would also be interesting but with a low priority for us.

Other then that, the module works like a charm on a custom openstack deployment ! Great Job !

**Comment by zifeo** [comment]
@bagutzu Happy to hear! Sure, this would definitely be useful for others. Feel free to open a PR :)

Note that there is still a caveat with the OpenStack cloud controller not being able to query the node (not a big issue, yet it might not handle well when there is a disk pressure or small network cut). A fix is tracked by https://github.com/zifeo/terraform-openstack-rke2/pull/9.

**Comment by zifeo** [comment]
This is fixed in v2.0.3.
